name: Build dummy
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
    paths:
      - "dummy/**"
  pull_request:
    branches:
      - "master"

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}-dummy"
  CRANE_NAME: "dummy"

jobs:
  docker:
    name: Push to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Login to ghcr.io"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: "${{ env.IMAGE_NAME }}"
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch,
            type=ref,event=pr
            type=ref,event=tag
            type=edge,branch=master
            type=sha
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "${{ env.CRANE_NAME }}/"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}